#TODO: Add targers to compile the program
GCC=gc
c

programa: main.c functions.c functions.h
	$(GCC) -o programa main.c functions.c

main.c: main.c functions.h
	$(GCC) main.c

functions.c: functions.c functions.h
	$(GCC) functions.c

.PHONY: clean
clean:
	rm *.o programa




